### PR TITLE
getting devise to work with users #21

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
Does it make sense to use before_action :authenticate_user! in the controller and user_signed_in? in each controller action? Is that overkill to make sure a user is signed in to affect the database when they can't get to the page without authentication anyway?

**Comment by clburns107** [comment]
Also, Where do the CSS files for Administrate live?

**Comment by clburns107** [comment]
Also I created a controller for Users but then so did Devise when I installed it.  Which one is the one being utilized? Can i just delete mine?

**Comment by sumeetjain** [comment]
> Also I created a controller for Users but then so did Devise when I installed it. Which one is the one being utilized? Can i just delete mine?

Yes, delete yours.

**Comment by sumeetjain** [comment]
> Also, Where do the CSS files for Administrate live?

Hidden away, in the gem's internals. You shouldn't do much/any CSS work on Administrate components. It's not worth the cost, probably.

**Comment by sumeetjain** [comment]
> Does it make sense to use before_action :authenticate_user! in the controller and user_signed_in? in each controller action? Is that overkill to make sure a user is signed in to affect the database when they can't get to the page without authentication anyway?

Are you still talking about Administrate? That is, are you trying to restrict access to the admin system? Or do you want to restrict access for users to all the other pages too?

**Comment by clburns107** [comment]
I want to restrict access to the admin system.  All other pages should be visible by the public.  
I want to add a logout button that logs an admin out of the admin system. Im not sure where that controller is in devise.  Theres nothing in the actual controller. I'm not really sure how devise infiltrates my controllers because it looks like theres nothing there but things just magically work sometimes

**Comment by clburns107** [comment]
Also should i delete the Application controller that devise did not create?

**Comment by sumeetjain** [comment]
I would check out http://administrate-prototype.herokuapp.com/getting_started. The part of it that's relevant here is:

> The installer adds some new routes to your config/application.rb, and creates a controller at app/controllers/admin/application_controller.rb
> 
> The Admin::ApplicationController can be customized to add authentication logic, authorization, pagination, or other controller-level concerns.

Check out app/controllers/admin/application_controller.rb and you should find some pre-commented-out stuff related to authentication.

I know this is only a piece of the information you're looking for, but I think it's best to stick with one thing at a time. After you get authentication-for-admin working, we can check back in to work on that logout button.

**Comment by sumeetjain** [comment]
> Also should i delete the Application controller that devise did not create?

Hm. I don't think so. Is that the one that Administrate created? I don't think there are ever needs to delete ApplicationControllers.

**Comment by clburns107** [comment]
ok user authentication works for admins.  Im still not sure on how to log out. Right now in order to log out i have to clear my cache and cookies.

**Comment by sumeetjain** [comment]
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=devise%20logout%20link led me to https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template, which shows me:

`<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>`

So your goal is to get that to show up somewhere in Administrate's views.

How do you modify Administrate's views?

Run `rails generate` to see a list of generator commands, because Administrate should give you a way to generate the views that it's hiding behind the scenes. You're looking for one that lets you modify the sidebar, because that's a sensible place for the logout link.

Then you'll want to try adding the logout link there.

**Pull request merged**
